describe('Thinker', () => {
  require('./_index/do.js')
  require('./_index/_intoSync.js')
  require('./_index/_callSync.js')
  require('./_index/_waitUntilCanSync.js')
  require('./_index/_doSync.js')
  require('./_index/_tryToTriggerBackgroundInitializeCompletelySync.js')
  require('./_index/_sendSyncRequest.js')
  require('./_index/_updateLocalData.js')
})
